[theme]
base = "light"
primaryColor = "#5C6AC4"  # Calm creative blue-violet
backgroundColor = "#FAFAFB"  # Very light, clean background
secondaryBackgroundColor = "#F0F2F6"  # Soft gray card background
textColor = "#222222"  # Deep charcoal for good readability
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
